### ISSUE TITLE
Google Login fails with requestCode 10 (DEVELOPER_ERROR)

### ISSUE THREAD

**Issue by gazlaws-dev** [aspirebudgetingmobile/aspirebudgeting_android#11]
> This almost certainly means you have not properly registered your SHA1 and Package Name in the Google API console: https://developers.google.com/identity/sign-in/android/start
https://github.com/googlesamples/google-services/issues/360#issuecomment-381648685

So what changes do we need to make after forking this project, to get the sign-in to work?

**Comment by mohitathwani** [comment]
You really shouldn’t have to do anything. @akashsarkar188 can you help out?

**Comment by akashsarkar188** [comment]
Hello @gazlaws-dev, actually when you fork and start the project on your desktop you work with your personal SHA1 and not the one which we have registered in the console, that's the reason google login is throwing Exception 10. To resolve it, you need to generate an OAuth client ID using your SHA1 (Debug) !

**Comment by gazlaws-dev** [comment]
Thanks! For future reference: https://developers.google.com/identity/sign-in/android/start-integrating
