### ISSUE TITLE
Update logic for fetching categories and groups

### ISSUE THREAD

**Issue by mohitathwani** [aspirebudgetingmobile/aspirebudgeting_android#14]
As of now, we are using "Dashboard!H4:O" to compute the list of categories and groups and while parsing his information, we are checking if the size of a returned element is 1 to decide whether it is a group. This is incorrect since in v3.2 of the sheet you can have group totals. We should fetch "Dashboard!F4:O" and check if the first element is "✦", representing a group. This will ensure the overall logic for parsing remains the same across all the versions of the sheet.

**Comment by akashsarkar188** [comment]
Done
